### ISSUE TITLE
More sophisticated table with sortable / filterable / searchable columns

### ISSUE THREAD

**Issue by sschuberth** [composablehorizons/composablesui#1]
Specifically, I'm looking for something like this React component:

![image](https://github.com/composablehorizons/composablesui/assets/349154/d6730dae-1c25-4bfb-92b4-47580df7e8bb)

![image](https://github.com/composablehorizons/composablesui/assets/349154/5d196dd3-3b94-40ed-96d1-1ba25fa7ed14)

**Comment by alexstyl** [comment]
Just wanted to confirm that more interactive tables are in the TODO. No promised dates yet but there is going to be a revamp on the tables with more interactivity.

Feel free to comment on what functionality you need, as this will make it much simpler for me to include them

**Comment by alexstyl** [comment]
New interactive table are now available on [Composables UI](https://composablesui.com/components/application-ui/components/tables).

I added component examples for:
- Simple Table
- Table with sortable headers
- Table with selectable rows
- Scrollable table
- Table with pagination
- With merging columns on on mobile
- With hidden columns on on mobile
- Table with filtering


Closing this as done
