### ISSUE TITLE
[Component: Product list with carousel on mobile] How do I import ComposeTheme?

### ISSUE THREAD

**Issue by javac9** [composablehorizons/composablesui#11]
This component contains several ocurrences of this line:
`style = ComposeTheme.textStyles.base.copy(fontWeight = FontWeight.Medium)`

I cannot import `ComposeTheme`. How do I overcome that?

**Comment by alexstyl** [comment]
`ComposeTheme` is a CMP library that sets up defaults such as the text styles you see there. You can import it by adding the dependency:

```kotlin
dependencies {
    implementation("com.composables:composetheme:1.2.0-alpha")
}
```
More info at https://github.com/composablehorizons/composetheme

If you do not want to use it, you can change it to your `MaterialTheme.typography.XXX` theme :)

**Comment by alexstyl** [comment]
PS: the fact you were not able to tell how to add it is an issue from my side. I will make sure that all examples contain the required imports later today
