### ISSUE TITLE
New website layout

### ISSUE THREAD

**Issue by javac9** [composablehorizons/composablesui#13]
Hi Alex, I have to admit that I don't find the new layout very practical for the following reasons:

* lacks good visual component overview
* bigger components have lots of code and one needs to do lots of scrolling in the left pane in order to reach next component
* when browsing the components I don't prefer seeing code over seeing how the actual component looks like. Once I decide which component I want to use, only then am I interested in taking a look at the code in order to check how something has been done or to copy it

I didn't mind the old look, really and would like to have it back, at least as an alternative?

**Comment by alexstyl** [comment]
thanks for the feedback, which is totally fair

keep in mind you can view all components at https://composablesui.com/components

could you let me know whether you think the new preview of the component itself is better or worse?

thanks

**Comment by alexstyl** [comment]
and just to confirm you are saying that doing the same on https://composablesui.com/components/ecommerce-ui/components/checkout 's single step one doesn't scroll?

Trying to understand if the component doesn't scroll as expected or this is a visual issue (ie not visible scrollbars)

**Comment by alexstyl** [comment]
Regarding the long code blocks, I made it so that you have to 'expand' longer blocks. Hopefully this resolves the scrolling issue.

Kindly let me know about the scrollbars

<img width="772" alt="Screenshot 2024-08-29 at 18 29 19" src="https://github.com/user-attachments/assets/0ea33504-07fd-40f0-9559-8f82fb35db41">
