### ISSUE TITLE
[Sidebar] Should stay in position after a component/screen has been selected

### ISSUE THREAD

**Issue by javac9** [composablehorizons/composablesui#20]
Hi, 

at the moment, after a component or a screen example has been selected/clicked, at least in my Chrome browser, the sidebar kinda "reloads" and defaults to top position. This is really annoying when one is browsing through the items in the bottom half of the sidebar.

Any way you could make it remember the position it was in before the selection?

**Comment by alexstyl** [comment]
I agree. That seems very annoying.

Just pushed an update so that the currently selected item is highlighted and visible.

Here is an example: https://composeexamples.com/components/application-ui/screens/profiledetails

Let me know if that fixes your issue

**Comment by alexstyl** [comment]
With pleasure. If anything else comes up, kindly open a new issue
