### ISSUE TITLE
More details on how to work with/implement expandable card composables

### ISSUE THREAD

**Issue by willnwalker** [composablehorizons/composablesui#4]
Would appreciate details on how to make expandable cards with a header element with constraints. Specifically implementing card headers that maintain an aspect ratio up to a certain width, and therefore have a maximum height (for larger displays where list items shouldn't get obscenely big). Also looking for a primer on how to work with animated visibility and growing/shrinking container composables (animating visibility for the expanded view of a card is tricky to understand)

**Comment by alexstyl** [comment]
Have u seen the [ExpandableCard](https://composablesui.com/components/components/cards) component?

**Comment by willnwalker** [comment]
Yes, this is a response to that component. I had to add some features which I felt some other users might want knowledge of how to implement.

**Comment by willnwalker** [comment]
Solution I arrived at was a composable that wrapped Box taking a maxHeight param. That param is used to constrain the nested box's height, and its width is established by aspect ratio until that height is reached by using size callback modifier

**Comment by alexstyl** [comment]
@willnwalker I need more context to understand your request.

If you have a specific component you would like to see (ie some specific UI patterns you have seen in an app), let me know. 

What you are describing sounds like instructions of how to use specific APIs, which you can find in Compose's documentation.


If you don't have a specific component, kindly close this issue.
