### ISSUE TITLE
Rich Text Editor

### ISSUE THREAD

**Issue by adhithya90** [composablehorizons/composablesui#6]
Rich text editing is something that is extremely complicated to implement. I've tried implementing a few variations with BasicTextField but the number of edge-cases make it hard to implement something that is robust enough. It will be of immense help if there existed a Rich Text Editor with bold, italic, underline, links, and modifiable types of typography such as Header, Subheader, Title etc.

**Comment by alexstyl** [comment]
This kind of component might be way too complex for what Composables UI is for.

What is your use case?
