### ISSUE TITLE
[Component: Profile Details Screens] Expecting a top level declaration in IntelliJ

### ISSUE THREAD

**Issue by javac9** [composablehorizons/composablesui#8]
I want to use the Profile Details Screens component. However, IntelliJ is complaining related to this spot in code: 

that "Expecting a top level declaration in IntelliJ" and the red squiggly lines are shown for each line of that block.

EDIT from Alex: Removed the code as it's part of a paid component

**Comment by alexstyl** [comment]
Are you using the Material Compose dependency in your project?

**Comment by alexstyl** [comment]
I see what you mean. it is indeed outside a composable function. no component example in composablesui.com is inside a composable function.

you would need to place them inside your own screen composable
